version:  "3.7"
services:
  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ~/bodycsm/postgres:/var/lib/postgresql/data
  redis:
    image: redis:7.0.6
    ports:
      - "6379:6379"
    volumes:
      - ~/bodycsm/redis:/data
  bodycsm:
    image: hungtpplay/bodycms:latest
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=postgres
      - DB_SSLMODE=disable
      - DB_SCHEMA=public
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PORT=8080
    command: ["go", "run", "main.go"]
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis
  jaeger:
    image: jaegertracing/all-in-one:1.27
    ports:
      - "16686:16686"
      - "14250"
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - 9411:9411
  otel-collector:
    image: otel/opentelemetry-collector
    container_name: otel-collector
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP http receiver
      - "55679:55679" # zpages extension
    depends_on:
      - jaeger
      - zipkin
      - bodycsm
