version:  "3.7"
services:
  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ~/bodycsm/postgres:/var/lib/postgresql/data
  redis:
    image: redis:7.0.5
    ports:
      - "6379:6379"
    volumes:
      - ~/bodycsm/redis:/data
  bodycsm:
    image: hungtpplay/bodycms:latest
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=postgres
      - DB_SSLMODE=disable
      - DB_SCHEMA=public
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: ["go", "run", "main.go"]
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis