basePath: /
info:
  contact:
    email: hungtp.play@gmail.com
    name: API Support
  description: API that BodyCMS provides to its users.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: BodyCMS API
  version: 0.0.1
paths: {}
swagger: "2.0"
